### ISSUE TITLE
Cache component generates too long filename for encrypted filesystem

### ISSUE THREAD

**Issue by korotovsky** [doctrine/cache#118]
I have `Ubuntu 14.04.2 LTS` with encrypted filesystem. It's known limitation, but I think Doctrine should work on such configurations.

As a result doctrine generates cache on each request.

```
rename(/data/www/sf2-app/app/cache/dev/annotations/3a/swaplxj6AI,/data/www/sf2-app/app/cache/dev/annotations/3a/5b5b435d4564737465725c42756e646c655c41707042756e646c655c456e746974795c557365725c557365722466697273744e616d65405b416e6e6f745d5d5b315d.doctrinecache.data): File name too long
Context: { "type":2,"file": "/data/www/sf2-app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php", "line":254,"level":28928,"scream":true}
```

**Comment by Ocramius** [comment]
@korotovsky what is the limitation, exactly? Any document describing the max length?

**Comment by korotovsky** [comment]
@Ocramius Actually, it's a bug :)) https://bugs.launchpad.net/ecryptfs/+bug/344878 and in my case it's 143 bytes, and it doesn't matter how many sub-directories we have (looks like)

http://unix.stackexchange.com/a/32834

> Clearly, that 7 character filename now requires more than 7 characters to be encrypted. Empirically, we have found that character filenames longer than 143 characters start requiring >255 characters to encrypt. So we (as eCryptfs upstream developers) typically recommend you limit your filenames to ~140 characters.

**Comment by Ocramius** [comment]
Yes, but is there a mathematically proven file name length that fits?
Otherwise I'll just close the issue as "can't fix", and add a documented
limitation.

**Comment by korotovsky** [comment]
@Ocramius My quote above is a answer of author/maintainer eCryptfs. See his full answer: http://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs/32834#32834

As I understand, eCryptfs adds overhead to filename length to encrypt filename and store some metadata to it. That's why the original filename can't be bigger than 143 characters.

**Comment by Ocramius** [comment]
The problem I see there is the word `Empirically`. If there is no clear cut on how this works on such systems, then we can't afford supporting it and all the edge cases it comes with.

I'd rather suggest having a specific `eCryptfs` adapter than coding support for it in this one.

**Comment by korotovsky** [comment]
I think we should not consider it as a magic value, at least because filename encrypts every time by the same algo with the same result. This algo has overhead and, of course, we can try to find it in the source code... but I don't see any reason why we should not trust this value. Especially when:

 * This bug https://bugs.launchpad.net/ecryptfs/+bug/344878 created 2009-03-18 and nothing has changed since this time.
 * The maintainer talks about it very clear: that it's a design limitation. 
 * This bug is considered 'fixed' by the upstream maintainers.

Cut from https://bugs.launchpad.net/ecryptfs/+bug/344878:
```
IMPORTANT: eCryptfs can only store filenames of up to 143 characters when filename encryption is enabled. The remaining 112 characters are used for storing metadata such as the encrypted filename prefix, the signature of the filename encryption key, and an identifier for the cipher used, as well as random bytes to make /foo/file and /bar/file encrypt to different ciphertext and padding bytes to achieve proper cipher block size alignment.

This bug is considered 'fixed' by the upstream maintainers. The eCryptfs kernel error message has been reduced to a debug level log message and eCryptfs now correctly reports its maximum supported filename length through the statfs() syscall. This is all that can be done without implementing a completely new encrypted filename design. A design that allows 255 character filenames without introducing other design limitations has not been identified and no one is currently working to come up with such a design.

Please do not add comments or create new bugs saying that mv reports 'File name too long' or that you can't create a long filename in your eCryptfs mounts. It is an unfortunate design limitation that cannot be avoided at this time.

Please do create new bugs when an application generates filenames that are too long to be stored in an eCryptfs mount. The application may be able to use the statfs() syscall to check the filename length limits of eCryptfs. Note that this does not include something like a torrent or ftp client trying to download a file with a long filename. The application is not generating the filename in those cases, it is just downloading the file that the user told it to download.
```

**Comment by zeroedin-bill** [comment]
The Windows path length limit of 259 characters is *ludicrous* as it is. There are plenty of encrypted filesystems out there that don't have such limits. If you really need to support eCryptfs's bizarre path length limit of *143 characters*, extend FileCache in your app, reimplement getFilename, and use that.

**Comment by zhil** [comment]
I have the same problem.

@zeroedin-bill just wonder - whats point of creating files like 5b5b435d41707042756e646c655c436f6e74726f6c6c65725c5573657273436f6e74726f6c6c65722375736572496e76697465536f6c646965725468616e6b73416374696f6e405b416e6e6f745d5d5b315d.doctrinecache.data ?

thanks for pointing out, how it could be fixed. But this feature is just strange.

**Comment by tofra** [comment]
Rsync is also complaining :(
rsync: recv_generator: failed to stat "<82 character string>/var/cache/dev/annotations/00/5b464f535c5573657242756e646c655c436f6e74726f6c6c65725c4368616e676550617373776f7264436f6e74726f6c6c6572236368616e676550617373776f7264416374696f6e405b416e6e6f745d5d5b315d.doctrinecache.data": File name too long (36)

**Comment by korotovsky** [comment]
I made the title a bit more generic. So, @Ocramius I'm not alone with it. It make sense to reopen this issue.

**Comment by stein189** [comment]
What is the current status on this issue? I am facing the same problem.
