### ISSUE TITLE
Maybe it's time to release new tag 1.6?

### ISSUE THREAD

**Issue by ovr** [doctrine/cache#120]
Hey!

Maybe it's time to release new tag 1.6?

@Ocramius 

Thanks

**Comment by ovr** [comment]
Via cache driver for `apcu` is pushed to master branch aka 1.6.x-dev
I started to hate compile https://github.com/krakjoe/apcu with bc module

**Comment by Ocramius** [comment]
Closing: not an issue.

Will tag when I have time (which is not now, sadly)
