### ISSUE TITLE
MemcacheCache & Compression

### ISSUE THREAD

**Issue by Pierre-Henri-Bourdeau** [doctrine/cache#123]
Hi Doctrine community!

I don't know if I'm asking this question at the right place but I'll give a try.

We are using Doctrine & Memcache in our company and I was looking for enabling compression as it is provided by PHP (http://php.net/manual/fr/memcache.set.php).
But it seems that Doctrine\Common\Cache\MemcacheCache::doSave doesn't allow an argument to do so.

Is it a feature that would be released soon? Is it possible to fork the project and suggest it?

Thanks in advance for your help.

**Comment by Enleur** [comment]
I guess you should extend MemcacheCache class and override doSave method

**Comment by Pierre-Henri-Bourdeau** [comment]
Thanks for your answer Enleur

**Comment by Ocramius** [comment]
@Pierre-Henri-Bourdeau this may well be added to core, but we need to be sure that all environments running memcache support that flag (and that it is worth doing that).

Therefore, closing this issue until it is proven that such a change has no performance/compatibility implications.

(alternate solution already provided by @Enleur)
