### ISSUE TITLE
Filenames are too long for windows

### ISSUE THREAD

**Issue by enumag** [doctrine/cache#124]
Caching was not working for me properly on my computer so I tried to dig up why. Turns out that this [rename](https://github.com/doctrine/cache/blob/fb8eaa0b612b543d10f09df8eb16b47dd976e97a/lib/Doctrine/Common/Cache/FileCache.php#L254) call often fails with `Warning rename(...) Invalid argument`. Of course the error was suppressed by the `@` operator so it took a while to find. The warning happens when the path is too long (probably 256 characters is a limit).

I tried to upgrade to dev-master, it didn't help.

**Comment by enumag** [comment]
It seems that [this](https://github.com/doctrine/cache/blob/fb8eaa0b612b543d10f09df8eb16b47dd976e97a/lib/Doctrine/Common/Cache/FileCache.php#L140 is buggy because the getFilename method returns a 280 characters long path.

**Comment by enumag** [comment]
Well of course it is buggy. See #125.

**Comment by zeroedin-bill** [comment]
see https://github.com/doctrine/cache/pull/122

**Comment by zeroedin-bill** [comment]
@enumag Can you run the branch from #122 and verify tests pass?

**Comment by enumag** [comment]
Sure, sorry for the duplicate issue. :-(

**Comment by zeroedin-bill** [comment]
@enumag No worries - I need to merge the thing I think :(

**Comment by enumag** [comment]
Ok the tests failed for me quite horribly. I'm probably doing something wrong because they failed on master branch as well. All I did was this:

```
composer up
.\vendor\bin\phpunit
```

What did I miss?

**Comment by enumag** [comment]
Oh the fails are because I don't have APCU installed and the tests didn't skip.

**Comment by enumag** [comment]
Damn that hotfix branch can't be installed by composer. Probably because of `#` in branch name.

Anyway I removed the ApcCacheTest.php and ApcuCacheTest.php and run the tests again. Many tests skipped but none failed. I'm guessing that filesystem cache tests are never skipped so it should be fine. :-)

I've tried running tests on master branch as well. Sure enough there are four filesystem related tests that failed which means the hotfix indeed fixed some bugs.

**Comment by Gamesh** [comment]
hi, the issue also occurs if running on vagrant, and unfortunately your provided solution for windows does not work here, as doctrine runs inside a VM and thinks it's a linux box but infact files are stored on windows.

do you really need that much length in file names ? maybe just simplify things and truncate the file length on all OSes
