### ISSUE TITLE
ApcuCache() not in 1.5 releases?

### ISSUE THREAD

**Issue by rhukster** [doctrine/cache#129]
Is there a reason ApcuCache() which is in master is not getting included in the 1.5 releases? Would be nice to make that PHP 7 APCu support available.  Cheers!

**Comment by Tobion** [comment]
I.5.x are patch releases. Not a feature release.

**Comment by rhukster** [comment]
Is a 1.6 release planned soon?

**Comment by Ocramius** [comment]
@rhukster it will likely be tagged after #117 is merged.
