### ISSUE TITLE
Updates for accepted PSR-6 standard

### ISSUE THREAD

**Issue by scaytrase** [doctrine/cache#131]
[PSR-6](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-6-cache.md) have been approved recently. Any plans on updating the cache libraries?

PSR-6 covers the following interfaces as single one

* Cache
* ClearableCache
* FlushableCache
* MultiGetCache

https://github.com/php-fig/cache

**Comment by Ocramius** [comment]
Duplicate of #119
