### ISSUE TITLE
AutoExpiration index of MongoCollections not configured automatically

### ISSUE THREAD

**Issue by holtkamp** [doctrine/cache#139]
After switching to Doctrine\Cache using the MongoDBCache I noticed the MongoDB Collections were growing / expired entries were not removed automatically.

After having a look at the source, it seems the use of [MongoDB's automatic purging functionality is not 'enforced'](https://github.com/doctrine/cache/blob/e0ef9e9833ca024d251e77e8d82a00ca92b0aa71/lib/Doctrine/Common/Cache/MongoDBCache.php#L44-L48). Would it make sense to do this? Something like this which can be invoked in the constructor.

``` php
    private function createIndex()
    {
        $this->collection->createIndex(
            array(self::EXPIRATION_FIELD => 1),
            array(
                'background' => true, //Builds the index in the background so that building an index does not block other database activities.
                'expireAfterSeconds' => 0 // Have entries expire directly (0 seconds) after reaching expiration time
            )
        );
    }
```

Note that prior to MongoDB the function was called [ensureIndex()](http://php.net/manual/en/mongocollection.ensureindex.php), which is now an alias of [createIndex()](http://php.net/manual/en/mongocollection.createindex.php). Ensuring an index exists sounds more appropriate to me, but hey, it is deprecated :smile: 

Also see our previous cache driver: https://github.com/AntonStoeckl/Zend_Cache_Backend_Mongo/blob/aa1ac7cf415bb96fd114a9717e5ab88822462ed5/library/Zend/Cache/Backend/Mongo.php#L548-L567

**Comment by Ocramius** [comment]
Yes, that makes sense /cc @alcaeus

**Comment by alcaeus** [comment]
Yes, using that functionality makes sense ;)

**Comment by holtkamp** [comment]
@Ocramius , you labeled it as a bug, not sure whether that is the case, more new functionality?

I can come up with a PR, might take some weeks before I can find time though...

**Comment by Ocramius** [comment]
> @Ocramius , you labeled it as a bug, not sure whether that is the case, more new functionality?

Because of 

 > I noticed the MongoDB Collections were growing / expired entries were not removed automatically.
