### ISSUE TITLE
Misleading cache statistics

### ISSUE THREAD

**Issue by BreiteSeite** [doctrine/cache#141]
The default namespaceVersion (1) is always read, but never written into the cache. See: https://github.com/doctrine/cache/blob/e0ef9e9833ca024d251e77e8d82a00ca92b0aa71/lib/Doctrine/Common/Cache/CacheProvider.php#L212

This increments `get_misses` on memcache on every request.

I would propose to store the default namespaceVersion in the cache too (i think the existing behavior is not clean/logical that we only store versions >1. This makes version 1 a special case and i don't like special cases).

However, there are [tests that explicitly mention that this should not happen](https://github.com/doctrine/cache/blob/master/tests/Doctrine/Tests/Common/Cache/CacheProviderTest.php#L54). Should this assumption be changed and the tests refactored?

If so, i probably can submit a PR.

Thank you for your Feedback.

**Comment by Tobion** [comment]
See arguments in #91

**Comment by BreiteSeite** [comment]
I think these points should get reevaluated because i think the introduced issue was overlooked.

**Comment by Tobion** [comment]
To me performance and space requirements are more important than cache statistics.

**Comment by Tobion** [comment]
Btw, this problem would be solved by #96 anyway as it is a design issue.

**Comment by BreiteSeite** [comment]
Yes.. i'm aware of #96 but i want a simple yet fast "fix" before a huge refactoring hits a release.

However, regarding your points performance and space requirements: i don't believe that the write of the current namespaceVersion into the cache (which is only overhead if the cache is empty) is that much of a performance regression or do you have relevant analytics or benchmarks for this point? Also if you empty your cache, you take a massive performance hit anyways so i'm sure this one additional write into cache doesn't matter.

Also storing an integer value is a joke for space requirements.

Also cache statistics are crucial for performance analysis so i don't see why better statistics is contrary in your eyes to "performance requirements".

**Comment by Tobion** [comment]
This is per namespace. Btw, there is a workaround for you: just call `deleteAll` once. Or set the namespace version yourself using `CacheProvider::DOCTRINE_NAMESPACE_CACHEKEY`.
Also the cache statistics are wrong either way. Either the hits are wrong or the misses.

**Comment by BreiteSeite** [comment]
Your workaround is not valid in my eyes as cache flushing is part of the deployment (no php involved here) and calling deleteAll could erase a freshly populated cache and set the namespace version myself raises also a lot of technical debt (as probably no one after some weeks/months/years will know wtf is going on).

However, i half-agree with your point that cache statistics are wrong either either way. Yes, its probably suboptimal to store metadata for the caching algorithm in the cache itself (although thats great for consistency). But the cache statistics would get more correct in the sense that now i could catch real cache-misses which i'm now not able to, as my miss count is very high.

I don't want to apply knowledge of how doctrine/cache works/ruin my cache stats when i look at these stats.
