### ISSUE TITLE
Support for MongoDBCache on PHP 7 using ext-mongodb

### ISSUE THREAD

**Issue by holtkamp** [doctrine/cache#142]
Related to https://github.com/doctrine/mongodb/issues/239: in order to currently use [MongoDBCache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/MongoDBCache.php) `ext-mongo` is required. This extension has been replaced by [ext-mongodb](https://pecl.php.net/package/mongodb) on PHP 7.

Effectively this means that MongoDBCache can currently not be used on PHP 7.

**Comment by holtkamp** [comment]
Elaborating on this, what would be the most viable approach to support PHP 7?

What I can think of

1. create new class, for example "MongoDBCacheNG" (Next Generation ;)) which depends on ext-mongodb
- typecheck depending on which extension is loaded (ext-mongo / ext-mongodb) on either:
 - "MongoCollection" / "MongoDB\Collection"
 - "MongoDate" / "MongoDB\BSON\UTCDateTime"
 - "MongoBinData" / "MongoDB\BSON\Binary"
 - "MongoCursorException" / "MongoDB\Driver\Exception\Exception"
- new major version of Doctrine\Cache
 - only types as used in ext-mongodb and depend on PHP 7 only

I think the first approach would be the simplest in terms of development, testing and maintenance...

**Comment by Ocramius** [comment]
Handled in #222
