### ISSUE TITLE
Tagged caching support

### ISSUE THREAD

**Issue by mihai-stancu** [doctrine/cache#143]
Goal:
--------------------------------------------------------------------------------
I'm developing a "tagged cache" feature for `RedisCache` and `RiakCache` -- and other stores which support a datatype similar to `set` (`PredisCache`, `CouchBaseCache`, `MongoDBCache`, `Sqlite3Cache`).

I wanted to develop it stand-alone as an extension, unfortunately many private fields/methods make this burdensome via extensions (ex.: `RedisCache::getNamespacedId`, `PredisCache::$client`, `RiakCache::$bucket`).

I could either contribute my work so far if this feature would be of interest to the core deciders ...if not I would like to continue my stand-alone development but I would ask for support in opening up some new extension points (making some methods protected).

Concept:
--------------------------------------------------------------------------------
- Save an item
- Supply a list of tags associated with the item
- Fetch or delete lists of items based on their tags
 - all items which have *any of the these tags*
 - all items which have *all of the tags*

Redis implementation example:
--------------------------------------------------------------------------------
In `Redis` / `Predis` (and `Riak`) you can use the `set` datatype for this purpose:

```php
$cache->save($id, $value, $lifetime, $tags);

/* or */

$cache->save($id, $value, $lifetime);
$cache->tag($tags);
```
```
SET item_1_id item_1_value

SADD tag_value_1 item_1_id
/* ... */
SADD tag_value_n item_1_id
```

Retrieval would be similar:
```php
$cache->fetchByTags($tags);
```
```
SINTER tag_value_1 ... tag_value_n
```
```
MGET item_1_id ... item_n_id
```

**Comment by EmanueleMinotto** [comment]
What's the big difference between this issue and https://github.com/CEikermann/advcache?

**Comment by holtkamp** [comment]
:+1: on this, for the MongoDB CacheProvider, [this library](https://github.com/AntonStoeckl/Zend_Cache_Backend_Mongo/blob/master/library/Zend/Cache/Backend/Mongo.php) can provide some inspiration, we used it in production for quite a while and indeed, the tags feature is quite nice when having to remove cache entries matching a specific tag. For example "everything having to do with User X, Company Y, or Order Z.

**Comment by mihai-stancu** [comment]
@EmanueleMinotto in terms of tagging `advcache` applies the same concept but the implementation sits on top of Doctrine Cache (as a client) without integrating with it (ex.: as a CacheProvider) and does not gain access to the underlying client object.

My generic implementation (from the abstract CacheProvider) is pretty similar to advcache' but I would advise against using that implementation (ex.: when a particular client doesn't have support for `SET` datatypes) because it's not atomic / concurrency safe.

The Redis `SET` datatype for example:

- guarantees atomicity of adding / removing a member from the set -- this makes additions concurrency safe
- server-side set-intersection -- ensures the number of client-server communications are a fixed number, not dependent on the number of tags you use

**Comment by mihai-stancu** [comment]
@holtkamp apparently `MongoDB`'s `$setIntersection` operation would allow us to implement the same logic I envisioned for `Redis` / `Riak`.

P.S.: `MongoDBCache`'s implementation does not supply a native `fetchMultiple` even though it should be fairly trivial to add since Mongo can support `$in` operations.

**Comment by mihai-stancu** [comment]
I would appreciate any advice on the following topic:

0. Should the `save` operation include tagging?
 - could ensure one batch of commands sent to the server (item + all tags)
 - would alter the method signature of `save` (to add the tags parameter)
0. Should the `item` include all of the tags alongside the data?
 - this depends on the previous issue (need the tags available when saving the value)
 - could implement it like `$cache->doSave($key, serialize(array($value, $tags)));`
 - alternate implementation would be:

   ```php
   $cache->doSave($key, $value);
   $cache->doSave($key.'/tags', $tags);
   ```
 - would allow for correct/accurate cleanup of all removed tag members -- when removing some cache items by tags you should fetch all the tag-info related to all items and remove all cache keys from each tag.
 - without this, tags could potentially hold stale keys (for items which have been deleted)

**Comment by mihai-stancu** [comment]
Ping @guilhermeblanco 

@holtkamp / @EmanueleMinotto any advice?

**Comment by holtkamp** [comment]
Well, personally I would say that the ```save()``` method should anticipate for an extra parameter and store the tags information separate from the  item. The alternate implementation would be BC, but way more complex.

Personally I would say:
- ```save($id, $data, array $tags = array(), $lifeTime = 0)```

But that would be a BC break, so the most pragmatic approach would be:
- ```save($id, $data, $lifeTime = 0, array $tags = array())```

Or maybe wait for this RFC to land :smile: https://wiki.php.net/rfc/skipparams

**Comment by mihai-stancu** [comment]
That RFC is dead in the water, unfortunately :-).

@holtkamp I implemented the `save($id, $data, $lifeTime = 0, array $tags = array())` version in [another branch](https://github.com/mihai-stancu/doctrine-cache/tree/tagged_cache_support_coupled).

But it's important to know if @guilhermeblanco thinks this development is useful and worth integrating into the Doctrine Cache lib or if I should reorient my effort into a stand-alone lib.

**Comment by guilhermeblanco** [comment]
@mihai-stancu @holtkamp TBH I'm in the process of implementing Doctrine\Cache 2.0 and support like this on will be covered once implementation is ready.
So far I'm working on first and simplest driver (InMemory) to collect ideas and implementation strategy from other core developers. A quick draft of what's being done is available here: https://github.com/guilhermeblanco/cache
Right now you will likely see BC breaks with 1.0 and even API is not final. There're at least a hundred issues to be solved in my roadmap, but at the end we'll release a BC friendly library with 1.0. This may take a couple months to get ready and in the meantime my efforts are focused on this, and not considering massive feature addictions in the 1.X series.

**Comment by mihai-stancu** [comment]
@guilhermeblanco OK, since 2.0 will have support for tagging I'll just close this issue and the related PR. 

I'll roll my own tagged-caching lib on top of Doctrine Cache 1.0 until 2.0 comes out and we'll see where that gets us.

Thanks for the info!
