### ISSUE TITLE
FileCache Notice

### ISSUE THREAD

**Issue by Stajor** [doctrine/cache#147]
Hi.
I get a lot of notices in my error log from file vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php

I saw yours note 
```
note: error suppression is still faster than `file_exists`, `is_file` and `is_readable`
```

But may be you can add file_exists check optional?

**Comment by Ocramius** [comment]
Where do the notices come from? Any details? Can this be reproduced in the test suite?

**Comment by Stajor** [comment]
```
set_error_handler('my_error_handler');
function my_error_handler($errno, $errstr, $errfile, $errlin, $errcontext) {
   // write to error log
}
```
PS.
php 7.0.4

**Comment by Ocramius** [comment]
Right, and can you make that handler fail inside the test suite as well? We can probably avoid error suppression by stacking a new error handler in the execution of the cache fetch logic...

**Comment by Stajor** [comment]
Easy way to reproduce warning
```
        $cache = new \Doctrine\Common\Cache\PhpFileCache('/path_to_cache_folder/');
        set_error_handler(function($errno, $errstr, $errfile, $errlin){
            exit('Oops '.$errstr);
        });
        $cache->fetch('key');
```

**Comment by Ocramius** [comment]
Yep, I'm asking for an actual test case to be added to the test suite ;-)
