### ISSUE TITLE
Not possible to manually remove expired cache entries

### ISSUE THREAD

**Issue by holtkamp** [doctrine/cache#158]
To prevent caches from growing infinitely, expired entries should be removed. Some CacheProviders do this automatically, others don't. 

As part of a maintenance task that is executed periodically, it would be nice to be able to cleanup a cache: remove all expired cache entries. 

I noticed the existence of the following interfaces:
- `flushableCache`
- `clearableCache`

But was actually looking for an interface like:

``` php
interface cleanableCache{
    public function clean(DateTime $specificExpirationDateTimeNowOtherWise = null);
}
```

Is it on purpose that this kind of functionality is missing, or am I thinking in the wrong direction?

**Comment by Ocramius** [comment]
Seems like a good addition to me. Doing it automatically (internally) GC-style would likely cause issues in a production system, so it has to be an explicit concern.

**Comment by holtkamp** [comment]
ok, and what would be the way to proceed? I am thinking about:

1. introduce ```CleanableCache``` interface
2. start having specific specializations of the ```CacheProvider``` implement then
3. once all CacheProviders implement them (if even feasible), we can have the ```CacheProvider``` itself implement the ```CleanableCache``` interface

I am asking, since I probably won't have access to all specific technologies (Couchbase, Redis, ZendData, etc), so a gradual approach seems more appealing.

**Comment by Ocramius** [comment]
Most proper storage layers implement their own GC on their own.

The problematic bits are filesystem-based caches, including sqlite

**Comment by deancsmith** [comment]
Did you implement a strategy for this or do any work on this@holtkamp?

We are using the File caching rather heavily and are looking at a more in-library way of managing the cleanup of old cache entries.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
