### ISSUE TITLE
The CacheProvider::fetchMultiple method throw a warning level error

### ISSUE THREAD

**Issue by thenbsp** [doctrine/cache#159]
The CacheProvider::fetchMultiple method throw a warning when use memcached driver:

```
<b>Warning</b>:  array_key_exists() expects parameter 2 to be array, boolean given in <b>./vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php</b> on line <b>98</b><br />
```

the CacheProvider::fetchMultiple called CacheProvider::doFetchMultiple on line 92, mamached driver method MemcachedCache::doFetchMultiple is override CacheProvider::doFetchMultiple, called Memcached::getMulti [return false when items keys is not found](http://php.net/manual/en/memcached.getmulti.php), CacheProvider file on line 98 `array_key_exists($namespacedKey, $items)`, $items is false, so warning has been throw.

change CacheProvider::fetchMultiple on line 92:

``` php
$items = (array) $this->doFetchMultiple($namespacedKeys);
```

**Comment by Tobion** [comment]
There is already a PR for that: #138

**Comment by thenbsp** [comment]
why RP #138 is not merge to v1.6.0?

**Comment by SpacePossum** [comment]
the fix is merged, I think this ticket can be closed, please check @thenbsp

**Comment by Ocramius** [comment]
@SpacePossum thanks for noticing!
