### ISSUE TITLE
Memcached: doContains return true pretty much everytime if the stored value is "false"

### ISSUE THREAD

**Issue by riquito** [doctrine/cache#161]
The current implementation of [MemcachedCache::doContains](https://github.com/doctrine/cache/blob/4e3b8b9/lib/Doctrine/Common/Cache/MemcachedCache.php#L98) return `true` if the stored value is `false` and there is any kind of error code different from RES_NOTFOUND. 

If the error code is something like RES_NOTSTORED, RES_SOME_ERRORS or many others then `doContains` should return `false`.

**Comment by Tobion** [comment]
According to documentation, those return values cannot be returned from a simple get. So please provide a test case to prove something else.

**Comment by deeky666** [comment]
@Tobion unfortunately the docs are not revealing every implementation detail. [There are even tests that cover those constants](https://github.com/php-memcached-dev/php-memcached/search?utf8=%E2%9C%93&q=RES_SOME_ERRORS).

**Comment by Tobion** [comment]
I don't see a test for `get` and `RES_NOTFOUND`.

**Comment by riquito** [comment]
I can't provide a test, but I suppose that if you try a `get` after shutting down memcached you won't get RES_NOTFOUND (can't try right now). At present I'm getting in a production server result code 47, MEMCACHED_SERVER_TEMPORARILY_DISABLED, which causes `doContains()` to return `true` (don't know how to reproduce it on purpose).

**Comment by deeky666** [comment]
@Tobion https://github.com/php-memcached-dev/php-memcached/blob/607860c656a3cea22fb164c4eb71d36ec869c598/tests/experimental/getmulti_partial_error.phpt#L23

**Comment by Tobion** [comment]
That is a multiget. I already said twice that this ticket is about a simple get returning those states. Please read more carefully.

**Comment by riquito** [comment]
Here are some links to the implementation of `get` in the php memcached extension. 

`return_code` range from [BAD_KEY_PROVIDED](https://github.com/php-memcached-dev/php-memcached/blob/607860c656a3cea22fb164c4eb71d36ec869c598/php_memcached.c#L580) to [RES_PAYLOAD_FAILURE](https://github.com/php-memcached-dev/php-memcached/blob/607860c656a3cea22fb164c4eb71d36ec869c598/php_memcached.c#L656) to [pretty much anyting](https://github.com/php-memcached-dev/php-memcached/blob/607860c656a3cea22fb164c4eb71d36ec869c598/php_memcached.c#L628) (see [implementation of php_memc_handle_error](https://github.com/php-memcached-dev/php-memcached/blob/607860c656a3cea22fb164c4eb71d36ec869c598/php_memcached.c#L3033))

**Comment by Tobion** [comment]
Does that work?

```
return false !== $this->memcached->get($id)
            || $this->memcached->getResultCode() !== Memcached::RES_SUCCESS;
```

**Comment by riquito** [comment]
In libmemcached [a result can be returned only if RES_SUCCESS is true](https://github.com/trondn/libmemcached/blob/ca739a890349ac36dc79447e37da7caa9ae819f5/libmemcached/fetch.c#L67), so it should be correct. I find the first part of the expression misleading because we don't care about the returned value and `false` is a legitimate result. I'd write it differently because it's easier to reason about, but maybe that's just me.

```
$this->memcached->get($id);
return $this->memcached->getResultCode() === Memcached::RES_SUCCESS;
```

**Comment by JonasHaouzi** [comment]
:+1:

We're faced to the same issue.

**Comment by Ocramius** [comment]
A fix was provided via https://github.com/doctrine/cache/pull/181, but no tests are there, so I cannot merge it.
