### ISSUE TITLE
cache filenames are too long for windows when running on vagrant

### ISSUE THREAD

**Issue by Gamesh** [doctrine/cache#174]
this is related to #124 you fixed the issue on windows, but when running on vagrant the change does not solve the problem. If the host OS is Windows and guest OS (VM) is Linux, the code thinks it's running on Linux and creates very long filenames. Unfortunately there is no check to determine what the host OS is windows.

why this much entropy is needed in file names anyway ? 

maybe the whole code could be simplified to limit the path/filename to 260 chars on all OSes, that would solve the problem and wouldn't require any additional check of OS

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
