### ISSUE TITLE
PHP7 soft reserved keywords "object" in RiakCache.php

### ISSUE THREAD

**Issue by basvandorst** [doctrine/cache#179]
**File:**
`lib/Doctrine/Common/Cache/RiakCache.php`

**Message:**
Line 26: Name "object" that is reserved for future use (does not cause an error in PHP 7) used as a use statement alias `Riak\Object`

_More information_
[List of other reserved words](http://php.net/manual/en/reserved.other-reserved-words.php)

**Comment by Ocramius** [comment]
Invalid here - please report it to https://github.com/basho/riak-php-client

**Comment by basvandorst** [comment]
Done. https://github.com/basho/riak-php-client/issues/138

**Comment by christophermancini** [comment]
@Ocramius this actually does need to be opened here for two reasons...

- This code uses a completely outdated version of our library
- You would need to change line 26 to use an alias and update any references to the class in the file

**Comment by christophermancini** [comment]
Actually, after more detailed look, it makes use of this library to connect to Riak instead: https://github.com/php-riak/php_riak

**Comment by robocoder** [comment]
Let's close this. The php riak extension doesn't even build on php 7.0 or 7.1.

**Comment by lcobucci** [comment]
Closing in favor of #206.

**Comment by fatcrobat** [comment]
If you still struggle with this error on composer dumpautoload for instance, add the following to your project * `composer.json` autoload section.

```
"autoload": {
    "psr-4": {
      "Doctrine\\Common\\Cache\\": "src/Doctrine/Common/Cache/"
    },
}
```

This will look inside your `src/Doctrine/Common/Cache/` directory for classes inside the namespace `Doctrine\\Common\\Cache\\`. Inside this directory create an empty `RiakCache` class:

```
<?php

namespace Doctrine\Common\Cache;


class RiakCache
{

}
```

Run `composer dumpautoload` again and you are fine.
