### ISSUE TITLE
MemcacheCache::contains() always returns true on some machines

### ISSUE THREAD

**Issue by flack** [doctrine/cache#182]
When I run this snippet:

``` php
$cache = new Doctrine\Common\Cache\MemcacheCache();
$memcache = new Memcache();
$memcache->pconnect('localhost', 11211);
$cache->setMemcache($memcache);
$cache->flushAll();
$cache->deleteAll();
$key = uniqid('key');
var_dump($cache->contains($key));
var_dump($cache->fetch($key));
```

It outputs 

```
true
false
```

on certain machines, while on others it works fine. For example, on Ubuntu 16.10, `contains()` returns `false` as it should, but on Mac OS 10.10 (with Memcache 1.4.24 installed via `brew`), the output looks as above.

I've a bit through the code, and it seems that `$flags` in this line: 

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/MemcacheCache.php#L81

is `int(0)` in all cases. I'm having the same issue in scrutinizer's build environment, so it doesn't seem to be limited to Mac either. Not sure how to deal with this, but it makes the `contains()` function pretty useless

**Comment by JonasHaouzi** [comment]
We're having exactly the same issue.

As pointed out by @celtric, the logic looks _partially_ wrong:
```php
protected function doContains($id) {
    return false !== $this->memcached->get($id)
        || $this->memcached->getResultCode() !== Memcached::RES_NOTFOUND;
}
```

What if `$this->memcached->getResultCode()` returns another result **that is not valid**? For example `Memcached::RES_SERVER_ERROR` ? It might be safer to only confirm that the status is one of the successful codes.

@Ocramius - we could easily provide a fix for that if the logic looks good to you.

**Comment by flack** [comment]
@JonasHaouzi your issue is a different one actually. Mine is about the Memcache backend, yours is about Memcache**d**

**Comment by JonasHaouzi** [comment]
@flack Right, so easy to be confused... thank you for pointing it out.

**Comment by Majkl578** [comment]
`MemcacheCache` is already deprecated and can't be used with latest `doctrine/cache` as it doesn't work with PHP 7. Closing as wont fix then.
