### ISSUE TITLE
Feature request: Limited ArrayCache

### ISSUE THREAD

**Issue by rrehbeindoi** [doctrine/cache#205]
Feature request: a limited size version of ArrayCache

Use: Similar to ArrayCache, but without risking out-of-memory in bulk or long-running script cases.

Roughly a copy of the existing ArrayCache changing doSave
```php
    /**
     * {@inheritDoc}
     */
    protected function doSave($id, $data, $lifeTime = 0)
    {
        if (count($this->data) >= $this->cacheLimit) {
            $this->doFlush();
        }

        $this->data[$id] = [$data, $lifeTime ? time() + $lifeTime : false];

        return true;
    }
```

Due to ArrayCache::data being private, simply extending the ArrayCache class is not an option.

**Comment by Ocramius** [comment]
If you get to such a huge memory usage, in-memory caching is not a solution. Use APC/XCache or similar instead.

Closing as `invalid`

**Comment by billschaller** [comment]
If you need this, it's easy enough to implement it yourself.
