### ISSUE TITLE
RiakCache: rewrite to use native PHP riak client

### ISSUE THREAD

**Issue by robocoder** [doctrine/cache#206]
RiakCache currently depends on the riak extension which hasn't been updated in years and won't build on php7.0 or 7.1.

+1 to use @FabioBatSilva's https://github.com/php-riak/riak-client

**Comment by kimhemsoe** [comment]
A better approach would maybe be to write a new riak driver using https://github.com/php-riak/riak-client 

A small free advice here would that, if you need something here and now, it is to try and give it a go yourself and create a PR. No one here is getting paid for working on doctrine :)

**Comment by christophermancini** [comment]
The officially supported client performs faster than the client mentioned. https://github.com/basho/riak-php-client

**Comment by robocoder** [comment]
Really? I was referring to these benchmarks:
* http://riak-client.readthedocs.io/en/latest/performance.html

**Comment by christophermancini** [comment]
@robocoder yea, he took that benchmark on the old client as I was finishing the rewrite. I used his benchmarks to test the new client when I was fine and it is faster. Plus the official client is supported by basho engineers.

**Comment by christophermancini** [comment]
I will rerun the benchmarks and post the results.

**Comment by christophermancini** [comment]
@robocoder I have pushed the updates to the benchmark to my fork including results on PHP 5.4 through PHP 5.6. The [official Riak Client for PHP](https://github.com/basho/riak-php-client) is faster than the [php-riak](https://github.com/php-riak/riak-client) client except using PHP 5.4 over HTTP.

You can see the results here: https://github.com/christophermancini/riak-clients-performance-comparison#php-riak-clients-performance-comparison

Currently, our HTTP API bridge interface is compatible with PHP7, but our PB bridge interface is not. We are working on getting that updated for PHP7.

**Comment by robocoder** [comment]
Please re-review PR #213 and #215 now that Basho has updated their driver with list keys support.

**Comment by robocoder** [comment]
Status update, please and thanks. ;)

**Comment by Ocramius** [comment]
Riak support dropped, since it cannot run on 7.2 anyway
