### ISSUE TITLE
Escape colons in DoctrineNamespaceCacheKey[<cache namespace>]

### ISSUE THREAD

**Issue by Dadibom** [doctrine/cache#212]
Using the redis cache driver, I want to be able to use doctrine: as my namespace, as this will turn doctrine into a folder thus keeping redis browsable. However, as the colon is not escaped, this key stops working: DoctrineNamespaceCacheKey[doctrine:]

Maybe that key could be $namespace . 'DoctrineNamespaceCacheKey' instead? That would fix this error and put that key in the doctrine folder where it belongs :)

copied from https://github.com/doctrine/doctrine2/issues/6296

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
