### ISSUE TITLE
Couchbase support

### ISSUE THREAD

**Issue by abacaphiliac** [doctrine/cache#216]
hi Doctrine,

i'm looking for a PSR Couchbase implementation and came across a handful. of particular note is http://www.php-cache.com/en/latest/ which references Doctrine as being a Couchbase cache provider. i notice that the build does not install the extension, so tests are skipped. it appears that the adapter in this package expects an older version of the extension as well. current extension version(s) has \CouchbaseCluster and \CouchbaseBucket, or \Couchbase\Cluster and \Couchbase\Bucket instead of \Couchbase.

was wondering if i am on the right track or if i'm way off base. if i'm on to something, i was wondering if there is any interest in asserting the extension version in the existing adapter, and adding a new adapter for the more recent Couchbase extension. if so, i'd be interested in contributing.

**Comment by lcobucci** [comment]
@abacaphiliac if we take a look on the [provider history](https://github.com/doctrine/cache/commits/master/lib/Doctrine/Common/Cache/CouchbaseCache.php) we would see that it was created on 2013 and had never been updated. So you're completely right that it's using an outdated version of the extension.

Please do send a PR updating it, we would love that 😉

**Comment by Ocramius** [comment]
Please note that if any types change, a new implementation is preferable over a change in the current implementation.
