### ISSUE TITLE
Call to undefined function Doctrine\Common\Cache\apcu_fetch()

### ISSUE THREAD

**Issue by Laurent3170** [doctrine/cache#224]
When I clear the cache using `php bin/console doctrine:cache:clear-metadata --env=prod;`or `php bin/console doctrine:cache:clear-query --env=prod;` I receive the error `Call to undefined function Doctrine\Common\Cache\apcu_fetch()`.

The function `apcu_fetch()`is called from https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/ApcuCache.php but it doesn't exist in the file, neither in the project...
Do I miss something ?

**Comment by Ocramius** [comment]
It's the `ext-apcu` extension

On 1 Jul 2017 3:56 PM, "Laurent Marquet" <notifications@github.com> wrote:

When I clear the cache using php bin/console doctrine:cache:clear-metadata
--env=prod;or php bin/console doctrine:cache:clear-query --env=prod; I
receive the error Call to undefined function Doctrine\Common\Cache\apcu_
fetch().

The function apcu_fetch()is called from https://github.com/doctrine/
cache/blob/master/lib/Doctrine/Common/Cache/ApcuCache.php but it doesn't
exist in the file, neither in the project...
Do I miss something ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/cache/issues/224>, or mute the thread

**Comment by Laurent3170** [comment]
Thanks for your answer but can you explain a little bit more what should be done?

**Comment by lcobucci** [comment]
@Laurent3170 you should make sure that the mentioned extension is installed on your environment.

**Comment by Ocramius** [comment]
Closing as `invalid`

**Comment by Laurent3170** [comment]
@Ocramius I can understand that you close this, as it seems not to be an issue directly related to the project, but it's linked with, as the `apcu_fetch()` is called by it.
So it can't work if the external library is not installed, and it may be indicated somewhere (maybe it is but I haven't found).
@lcobucci thanks, I will have a look at it, when I have time. For the time being I can only find information about php-pecl-apcu

**Comment by Ocramius** [comment]
> So it can't work if the external library is not installed, and it may be indicated somewhere (maybe it is but I haven't found).

Yes, feel free to send a patch that verifies if the APCu extension is installed at boot time, but it's not really needed out of the box.

**Comment by Laurent3170** [comment]
Euh... I do need to understand before how it works and how to implement it... If I was able to do so, maybe I will have not set this issue ;-)

**Comment by Ocramius** [comment]
@Laurent3170 something like (pseudo-code):

```php
public function __construct()
{
    if (! function_exists('apcu_set')) {
        throw new SomethingSomethingException('APCu is not installed: please install APCu before using the APCu cache');
    }
}
```

**Comment by Laurent3170** [comment]
I am sorry to bother you but... I can't find how to install `ext-apcu` on Centos, I just can't find anything about `ext-apcu`.
On my dev (Ubuntu) I have `php-apcu` but no packages seems to exists for Centos...
Moreover, when I use the command `php bin/console doctrine:cache:clear-metadata --env=prod;` on my Centos prod server in a Symfony project, it works well, even if `apcu_fetch()` is not present in the above mentionned file and in another project, same server, it gives me the error.
I've looked around `composer.json` and they are the same.
I have installed `pecl install apc` but it doesn't solve the problem.

So... As I don't really understand differences between APC and APCu and neither OPCache, if you have "spare time" to give me a little bit of explanation, and/or where to search, it will be greatly appreciated! As when I move to production server, I always receive this, even when calling Console Command from crontab that don't call cache clearing.

**Comment by Ocramius** [comment]
`pecl install apcu`

**Comment by Laurent3170** [comment]
Argh... I have tried this but not looked at the error message.
```
pecl/apcu requires PHP (version >= 7.0.0-dev), installed version is 5.6.29
No valid packages found
install failed
```
So the problem is on my server... Thanks for your answer!

**Comment by Laurent3170** [comment]
So, the problem was on my server, it has been updated and the downgraded to php 5.6 without noticing me... But as clearing the cache doesn't work without apcu installed, I think it's better to prevent the user so I will try to work on a PR, as suggested, to do so. Just need to check a bit.

**Comment by Ocramius** [comment]
> downgraded to php 5.6 without noticing me

Wow, that's a new level of "managed hosting hell" :-\

**Comment by Ocramius** [comment]
Handled in https://github.com/doctrine/cache/pull/225
