### ISSUE TITLE
FileCache:: createPathIfNeeded can produce Warning: mkdir(): File exists

### ISSUE THREAD

**Issue by ivanbogomoloff** [doctrine/cache#226]
Invalid code here

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L223

I dont understand why
```php
false === @mkdir($path, 0777 & (~$this->umask), true) && !is_dir($path)
```

I think valid will be
```php
 !is_dir($path) && false === @mkdir($path, 0777 & (~$this->umask), true)
```

**Comment by Ocramius** [comment]
@ivanbogomoloff `mkdir` is silenced on purpose in https://github.com/doctrine/cache/blob/58f40845d8091b8cb768d6e3a49f685c8dff6928/lib/Doctrine/Common/Cache/FileCache.php#L223

Closing as `invalid`

**Comment by Ocramius** [comment]
Also, the reason for the conditional up there is that two concurrent processes may fight for directory creation, therefore `mkdir()` can fail while the directory is being created in a separate process, while `is_dir()` would then succeed.
