### ISSUE TITLE
Skipped adapters tests

### ISSUE THREAD

**Issue by lcobucci** [doctrine/cache#234]
We have some adapters that are old and their tests are not being executed by Travis:

- ApcCache: we could get it to run by installing `apcu-bc` but the tests fails
- CouchbaseCache: it seems the extension never got enabled in Travis and PHP 7 compatibility was only added on `v2.2.0` which might probably use a different API
- MemcacheCache: lastest release of `ext-memcache` was in **2013-04-07**
- RiakCache: latest release of `ext-riak` was in **2014-06-22** (and it's not compatible with PHP 7)
- WinCacheCache: we depend on `ext-wincache` and https://www.iis.net/downloads/microsoft/wincache-extension to be able to test it
- XcacheCache: according to http://xcache.lighttpd.net it's not compatible with PHP 7
- ZendDataCache: we obviously need Zend Data cache 

So my question is: are they still relevant? If not (at least for some), shouldn't we drop the implementation and trigger deprecation notes?

If some of those are indeed needed we need to find a way to ensure that the test suite is running, otherwise we cannot guarantee their behaviour.

**Comment by Ocramius** [comment]
> So my question is: are they still relevant?

In my opinion: no.

 * `ApcCache` is replaced by `ApcuCache`. `ext-apc` is not to be installed on 7.x systems, and we do only support 7.1+
 * `CouchbaseCache` is to be replaced by https://github.com/doctrine/cache/pull/229
 * `MemcacheCache` not to be used anymore: it is dead and defunct, and has no PHP 7.x support AFAIK
 * `RiakCache` should be replaced by a userland riak client.
 * `WinCacheCache` is not to be used unless you are willing to spend time on call with Microsoft's support.
 * `XcacheCache` also dead - OpCache marked the death of almost all other opcode caches anyway (even if they provide also userland cache interfaces)
 * `ZendDataCache` - not worth pursuing further: mainstream cache adapters are better here as well.

We should deprecate all of these, and stop actively supporting them.

 > If not (at least for some), shouldn't we drop the implementation and trigger deprecation notes?

Deprecation notices via `@trigger_error('message', \E_USER_DEPRECATED)`. We should start dropping tests for these classes too.

**Comment by Majkl578** [comment]
MemcacheCache + RiakCache + XcacheCache were deprecated in #267 as they don't work in PHP 7.1+.
CouchbaseCache was deprecated already.
WinCacheCache + ZendDataCache are still _supported_ so probably something for 1.8/2.0.

**Comment by bobvandevijver** [comment]
Memcache still works in PHP 7.3, so I created an MR to revert the deprecation: https://github.com/doctrine/cache/pull/306

**Comment by Ocramius** [comment]
Riak was dropped - remaining points still stand

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
