### ISSUE TITLE
PhpFileCache strange issues when used for Doctrine Annotations reader

### ISSUE THREAD

**Issue by TheCelavi** [doctrine/cache#236]
We are experiencing strange issue with PhpFileCache used for caching Doctrine annotations.

Issue can be reproduced, here is the PR where we stumbled upon that issue https://github.com/goaop/framework/pull/359 

Here is the troubling piece of code: https://github.com/goaop/framework/pull/359#discussion-diff-135615507R219

Namely, we have same configuration for all PHP versions. If we use PhpFileCache, test will fail on PHP 5.x, 7.0, passes on 7.1 and 7.2

If FilesystemCache is used, it passes on all PHP versions. 

What I have managed to see from cache directory is that PhpFileCache does not creates cache records on filesystem. 

I have to repeat again -> same configuration parameters are used for both drivers.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
