### ISSUE TITLE
RiakCache.php fails lint check in PHP7.2

### ISSUE THREAD

**Issue by kenorb** [doctrine/cache#239]
```
lint:
    [apply] Fatal error: Cannot use Riak\Object as Object because 'Object' is a special class name in vendor/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php on line 25
    [apply] Errors parsing vendor/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php
```

I'm using the following `composer.json` file:

```
{
    "require": {
        "doctrine/cache": "~1.4"
    },
    "prefer-stable": true
}
```

```
$ php --version
PHP 7.2.0beta1 (cli)
```

**Comment by Majkl578** [comment]
Well, that looks like a bug in Riak.

**Comment by lcobucci** [comment]
#213 introduces a more up to date implementation as well

**Comment by kenorb** [comment]
Related:

- basho/riak-php-client/issues/152
- basho/riak-php-client/pull/153
- basho/riak-php-client/pull/154

**Comment by kenorb** [comment]
Here is a more active repository: [PHPSocialNetwork/riak-php-client](https://github.com/PHPSocialNetwork/riak-php-client) to consider.

**Comment by ikodev** [comment]
Any news of this issue ?
I have temporary solve the problem on a SF project (SF 3.4, PHP 7.2) by removing the RiakCache.php (vendor/doctrine/cache/lib/Doctrine/Common/Cache/) such as it was only generating a Fatal Error due to "Object" occurrency.

**Comment by lcobucci** [comment]
@ikodev see #213, we need to adapt that branch to use `phpfastcache/riak-client` instead. We're just not having enough time to do it, so it would be amazing if you could send us a PR that replaces #213 =)

**Comment by Majkl578** [comment]
RiakCache extension is not compatible with PHP 7.1+ and is deprecated: #267.
Unfortunately it's not possible to remove the class in 1.x due to BC even though it's not usable anymore. :/
