### ISSUE TITLE
Only test is_writeable() if necessary

### ISSUE THREAD

**Issue by pdugas** [doctrine/cache#240]
I'm working on getting a Symfony app running up on Google App Engine's Standard PHP environment where the filesystem is read-only. Trying to use the EasyAdminBundle which uses FileCache under the hood. To make things work, I warmup the cache before deploying so many things are effectively pre-cached in production.
The `is_writeable()` test in the constructor for FileCache is causing the app to fail in production even though the directory and the pre-cached file within it are already there. I wonder if it would be possible to move that test elsewhere when an attempt is actually being made to write.

**Comment by Ocramius** [comment]
> I wonder if it would be possible to move that test elsewhere when an attempt is actually being made to write.

No, it is correct for it to fail eagerly, as it detects mis-configuration.

If your environment does not support `FileCache`, then don't use `FileCache`
