### ISSUE TITLE
resource cache

### ISSUE THREAD

**Issue by Gemorroj** [doctrine/cache#243]
https://github.com/doctrine/common/issues/828
I use PostgreSql. And use type `bytea`.
If i cache `bytea` resource (see note http://php.net/manual/en/ref.pdo-pgsql.connection.php).
I have cached string `0`.
I think possible cache resource as string with [stream_get_contents](http://php.net/stream_get_contents).
You may need to add in the documentation that the resources are not cached. Because such information is in the documentation I have not found.

Correct me if I'm wrong.

**Comment by Majkl578** [comment]
It's more tricky than _just_ converting it to string: If you cache a resource, I suppose you'd also expect to get a resource when loading the cache - there is probably no universal way to store such information though.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
