### ISSUE TITLE
Insufficient namespace isolation when flushing Redis-based cache

### ISSUE THREAD

**Issue by UlrichEckhardt** [doctrine/cache#244]
We have a Redis that is shared between different applications. Normally, the applications don't step on each other's feet because they all use different namespaces. However, when flushing the cache, this namespace seems to be ignored completely, so that it flushes the cache for all applications. In some cases that's a really bad thing, because computing the cached values takes considerable amounts of time.

Notes here:
 * The observations were made using 1.6.2. Checking the release notes doesn't indicate any change though, so the later releases are probably affected, too.
 * I think that not only the Redis implementation is affected. `flushAll()` doesn't provide any hint what to flush, so backend can only retrieve the namespace themselves or delete the whole cache.
 * I'll try to implement a fix for the Redis part and post updates when I have further info.

**Comment by UlrichEckhardt** [comment]
Suggestion:
```
    /**
     * {@inheritdoc}
     */
    protected function doFlush()
    {
        $pattern = $this->getNamespace() . '*';

        // configure Redis to retry when we get no keys back
        $this->redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);
        $it = null;
        while($keys = $this->redis->scan($it, $pattern)) {
            $this->redis->del($keys);
        }

        return true;
    }
```
A disadvantage is that some code might rely on the old behaviour, but that's unlikely considering that there is a namespace, which you use for separation. Also, this only fixes the Redis provider, not all the others.

As a workaround, we now have this class:
```
namespace Api\Caching;
class DoctrineRedisCache extends RedisCache
{
    /**
     * {@inheritdoc}
     */
    protected function doFlush()
    {
        $pattern = $this->getNamespace() . '*';

        $redis = $this->getRedis();

        // configure Redis to retry when we get no keys back
        $redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);

        // search and delete keys matching the namespace
        $it = null;
        while($keys = $redis->scan($it, $pattern)) {
            $redis->del($keys);
        }

        return true;
    }
}
```
...and according service configuration:
```
parameters:
    # replace vendor Redis cache implementation with our own
    # Reason is that flushing doesn't honor namespaces, which is bad on a shared
    # redis. See also https://github.com/doctrine/cache/issues/244.
    doctrine_cache.redis.class: Api\Caching\DoctrineRedisCache
```

**Comment by Tobion** [comment]
This is the expected and documented behavior https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FlushableCache.php#L15

> Flushes all cache entries, globally.

What you want to use is https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/ClearableCache.php

**Comment by UlrichEckhardt** [comment]
Thanks for that info, that explains it. However, I'd like to suggest two simple additions:

For FlushableCache:
```
Flushes all cache entries, globally.

For an alternative that only flushes the entries within the current namespace, see ClearableCache.
```

For ClearableCache:
```
Deletes all cache entries in the current cache namespace.

For an alternative that discards the cache globally, see FlushableCache.
```

In short, cross-reference the two functions with each other to make clear which one does which job.

Other than that, this issue can be closed.

Thanks!

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
