### ISSUE TITLE
Make protected CacheProvider::getNamespacedId()

### ISSUE THREAD

**Issue by wtorsi** [doctrine/cache#248]
Hi,
I see a lot native functions of some caches are not provided.
For example in `Redis` there is no possibility to work with hashed, lists, sets, no possibility to increment, decrement values.  In this case, extending `RedisCache` can help.
And it will be great, that for all this native functions, we can use your formatted `namespacedId`.

What do you think?

**Comment by Ocramius** [comment]
>  In this case, extending `RedisCache` can help.

That's actually complicating things. If you want to rely on the specific details of a `Redis` instance, then you should just use that: the interface/API provided by this package is defined in its interfaces, which are quite simplistic on purpose.
