### ISSUE TITLE
should lifeTime have int type declaration ?

### ISSUE THREAD

**Issue by serbancatalin** [doctrine/cache#249]
https://github.com/doctrine/cache/blob/e3fcea0d1af20ec7e236e37efaca378071adbae0/lib/Doctrine/Common/Cache/Cache.php#L62

Since it is used with null in 

https://github.com/doctrine/common/blob/a61bfddd39b887265117806e81cc6ca8da242fe1/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php#L200-L203

and adding a test for null lifeTime fails CouchbaseBucketCacheTest and PhpFileCacheTest
```php
     /**
     * @dataProvider provideDataToCache
     */
    public function testLifeTimeNull($value) : void
    {
        $cache = $this->_getCacheDriver();

        // Test saving a value, checking if it exists, and fetching it back
        self::assertTrue($cache->save('key', $value, null));
        self::assertTrue($cache->contains('key'));
    }
```
https://travis-ci.org/serbancatalin/cache/builds/352894953

**Comment by Ocramius** [comment]
Yeah, it should, but adding a type declaration can only be done if we enforce PHP 7.2l, as otherwise it counts as a BC break.

**Comment by serbancatalin** [comment]
I believe int type declaration was added in PHP 7.0

CouchbaseBucketCache usses it

https://github.com/doctrine/cache/blob/e3fcea0d1af20ec7e236e37efaca378071adbae0/lib/Doctrine/Common/Cache/CouchbaseBucketCache.php#L193

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
