### ISSUE TITLE
FeatureRequest: allow to define maximum cache entry size for CacheProviders in ChainCache

### ISSUE THREAD

**Issue by holtkamp** [doctrine/cache#273]
In certain situations, it would be nice if the ChainCache could "skip" a CacheProvider for cache entries that are considered "too big" to handle / to be useful for that specific CacheProvider.  

A fast cache like APCu, uses precious RAM memory. Storage of big items that are barely used are not useful to cache in the fast cache, while still depleting available RAM quickly. For each CacheProvider, a certain "max cache entry size" could be defined:

Something like
```php
//Use array keys to indicate max number of bytes, might be a bit verbose
$chainCache = new \Doctrine\Common\Cache\ChainCache([
    $arrayCache, //Key is '0' should be ignored. Probably everything below count($caches) should be ignored
    1024 * 1024 * 1024 => $apcCache,
]);

//Provide an array with the limits as second constructor parameter
$chainCache = new \Doctrine\Common\Cache\ChainCache(
    [
        $arrayCache,
        $apcCache,
    ],
    [
        null,
        1024 * 1024 * 1024,
]);

//Possibly with the cache class name as key
$chainCache = new \Doctrine\Common\Cache\ChainCache(
    [
        $arrayCache,
        $apcCache,
    ],
    [
        get_class($arrayCache) => null,
        get_class($apcCache) => 1024 * 1024 * 1024,
]);
```

The advantage is that a "big" cache entry can still be stored and eventually end up in a slower, but "cheaper" cache. While for small entries, the fast cache is hit...

Is this a viable idea? Would a PR be considered, or am I thinking nonsense. 

**Offtopic**
unfortunately, it seems APC**u** has dropped the `apc.max_file_size` configuration entry which *was* supported by APC: 

- http://php.net/manual/en/apc.configuration.php#ini.apc.max-file-size
- http://php.net/manual/en/apcu.configuration.php

I am [trying to find out why](https://github.com/krakjoe/apcu/issues/315)... anyone got an idea why?

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
