### ISSUE TITLE
Webserver’s default umask affects library behaviour

### ISSUE THREAD

**Issue by kinglozzer** [doctrine/cache#274]
The permissions for files/directories created by `FileCache` are impacted by the webserver’s default umask, which can vary between environments.

I’ve seen some other libraries that reset the umask to `0000` before performing filesystem operations:

```php
$old = umask(0);
$this->doSomeStuff();
umask($old);
```

Of course a workaround is to do the above in the implementation of this library, but it seemed worth suggesting incorporating this directly - IMO the library should “normalise” environment differences like that where possible.

Feel free to close if you disagree of course 😉

**Comment by Ocramius** [comment]
This was explicitly modified in https://www.doctrine-project.org/2015/08/31/security_misconfiguration_vulnerability_in_various_doctrine_projects.html, and won't be changed.

**Comment by kinglozzer** [comment]
Thanks for looking into this @Ocramius. I don’t think the issue linked necessarily blocks fixing this, e.g:

> The patches released today change all caches that execute code to always use a default mask of 0775 instead of 0777.
> - In case of Cache and Annotations we solve this by implementing a userland configurable umask that defaults to 0002. We apply this to every mkdir and chmod so that you can reconfigure to another mask if you must.

I don’t think that assertion is true. The default userland-configurable umask of `0002` _should_ result in a mask of `0775` on directories, but in my case the default umask for PHP is `0022`<sup>[[1]](#n1)</sup>, which means it’s impossible to achieve that without calling `umask(0)` first. Currently directories created by this library can’t have a more permissive mask than `0755` in my case, unless I call `umask(0)` myself at a higher level.

Setting the umask to `0`, then restoring it after creating files/directories, would still result in a mask of `0775` on directories (and `0664` on files) as intended. The only way the linked vulnerability could re-occur is if the userland-configurable umask had been expilcitly set to `0000`.

---

<a name="n1">1</a>. Apparently that’s because when starting Apache as root, it inherits the root user’s default umask of `0022`. In my particular case, I’ve resolved the issue by explicitly setting `umask 002` in `/etc/apache2/envvars`.

**Comment by kinglozzer** [comment]
For clarity, I’m suggesting containing all calls to `umask(0)` (and then resetting the umask back to the original value) inside each applicable method in `FileCache` - so there wouldn’t be any leak to the rest of an application. For example:

https://github.com/thephpleague/flysystem/blob/1.0.45/src/Adapter/Local.php#L372-L381
