### ISSUE TITLE
getFunctionMock of PHPMock does not work anymore

### ISSUE THREAD

**Issue by ypszi** [doctrine/cache#277]
When using `\phpmock\phpunit\PHPMock` trait `$this->getFunctionMock('\Doctrine\Common\Cache', 'apcu_fetch')` cannot mock `apcu_fetch` anymore because of function import in https://github.com/doctrine/cache/blob/d768d58baee9a4862ca783840eca1b9add7a7f57/lib/Doctrine/Common/Cache/ApcuCache.php#L9

**Comment by Ocramius** [comment]
This is expected and wanted: you are mocking details inside a third-party component, don't do that.

If you need to mock something, mock the `Cache` interface, and rely on that.

Closing as `invalid`.

**Comment by Majkl578** [comment]
This is also part of [Doctrine Coding Standard](https://github.com/doctrine/coding-standard).
