### ISSUE TITLE
PhpFileCache and opcache

### ISSUE THREAD

**Issue by Pasha19** [doctrine/cache#284]
When `PhpFilesCache` used with `opcache` enabled and `opcache.validate_timestamps = Off` `fetch` returns previous saved value. Opcache allows to invalidate cached files with [opcache_invalidate](https://secure.php.net/manual/en/function.opcache-invalidate.php). Is it possible to add this feature?

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
