### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by defro** [doctrine/cache#289]
The link in Readme file to documentation is broken.
I've got a 404 page when I go to 
http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/caching.html

**Comment by Majkl578** [comment]
Yep, but README in this repo. The link should be: https://www.doctrine-project.org/projects/doctrine-cache/en/latest/index.html

**Comment by lcobucci** [comment]
My bad, was too sleepy to read things properly
