### ISSUE TITLE
Drop ApcCache?

### ISSUE THREAD

**Issue by BenMorel** [doctrine/cache#290]
Facts:

- `ApcCache` has been deprecated in version 1.6
- Since v1.7.0, this library requires PHP `>= 7.1`
- As far as I know, [APC is dead since PHP 5.5](https://pecl.php.net/package-changelog.php?package=APC) (when zend opcache was introduced), and will definitely not work with PHP 7

So even though removing a class in a minor version is a semver violation, **does it make any sense to keep a class that cannot be used?**

**Comment by lcobucci** [comment]
@BenMorel even though it doesn't make much sense, one can still use it via `apcu_bc`. Therefore I wouldn't drop the class till next major...

**Comment by BenMorel** [comment]
Oops, I didn't know about `apcu-bc`. Forget it, then, let's wait until 2.0 to do some cleanup 👍 

Correct me if I'm wrong, there's no 2.0 branch yet, where I could submit a PR to remove `ApcCache`?
