### ISSUE TITLE
Cannot use Riak\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by BenMorel** [doctrine/cache#291]
I got this error while [playing](https://github.com/composer/composer/issues/7777#issuecomment-440268416) with the new preload feature that will come with PHP 7.4.

When bulk-preloading all dependencies (which is a functionality [composer might offer](https://github.com/composer/composer/issues/7777)), this error prevents the server from starting:

> Cannot use Riak\Object as Object because 'Object' is a special class name

I have to manually remove this file from my `vendor` directory if I want to preload the whole `doctrine/cache` library.

I can see that `RiakCache` is already deprecated, and that rewrites of this driver are planned (#206).

To be forward-compatible with PHP 7.4 and bulk-preloading of libraries (with or without composer), it would be nice to consider removing this file altogether.

I'm actually surprised that this class works in PHP 7.1, as `object` is a reserved word?

**Comment by Majkl578** [comment]
>I'm actually surprised that this class works in PHP 7.1

It's hard-reserved as of PHP 7.2.

**Comment by BenMorel** [comment]
Ah, true, I mixed versions!

**Comment by Ocramius** [comment]
Riak support dropped
