### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by pavlepredic** [doctrine/cache#292]
Given the [usage of a reserved word `object`](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RiakCache.php#L8) (reserved as of [PHP 7.2](https://secure.php.net/manual/en/reserved.other-reserved-words.php)), would it be fair to say that doctrine cache is incompatible with PHP 7.2 and this should therefore be reflected in the [composer.json](https://github.com/doctrine/cache/blob/master/composer.json#L27)?

**Comment by lcobucci** [comment]
@pavlepredic that's an upstream issue IMO and riak cache update is being handled on https://github.com/doctrine/cache/pull/213. The PR was put on-hold by the contributor - it would be amazing if you could help things there :+1:.

I wouldn't say that `doctrine/cache` itself is incompatible, though.

**Comment by pavlepredic** [comment]
Yes, I understand that the root cause is in Riak library, and I don't expect you to fix the underlying issue. I'm just suggesting that you specify in your library that PHP 7.2 is not supported. That would save people the headache of trying to figure out the weird errors stemming from some library they didn't even know they were using. In the long term, obviously it would be nice to either fix the issue upstream or remove RiakCache from doctrine/cache.

**Comment by Ocramius** [comment]
Cache itself is 7.2 compatible, riak cache is not. We can't block the entire library due to one adapter, sorry.

**Comment by pavlepredic** [comment]
There might just be a very simple solution for this problem. Simply alias the import here https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RiakCache.php#L8 as `RickObject` and replace the occurrences of `Object` with `RickObject` in the code below.
I could make a PR if you want.

**Comment by pavlepredic** [comment]
Here's the PR: https://github.com/doctrine/cache/pull/293. There's one more mention of `object` in the `isExpired` method typehint, but that's a lower-case object, so I'm guessing it's not supposed to be a Riak Object, right?

**Comment by pavlepredic** [comment]
Actually it seems that it **is** supposed to be a Riak object, but it was wrongly corrected by a CS fixer: https://github.com/doctrine/cache/commit/a6af9992e910dc6434274e25cb0aa6b3c32d7314

**Comment by Majkl578** [comment]
@pavlepredic If you are referring to https://github.com/doctrine/cache/commit/a6af9992e910dc6434274e25cb0aa6b3c32d7314#diff-d629badafdfaf4485ddc2acd2096f933R185, it only changed casing since CS assumes no errors in the code (and Object is an error), but `use Riak\Object` is still there and it was broken before too.

**Comment by reedy** [comment]
> @pavlepredic If you are referring to [a6af999#diff-d629badafdfaf4485ddc2acd2096f933R185](https://github.com/doctrine/cache/commit/a6af9992e910dc6434274e25cb0aa6b3c32d7314#diff-d629badafdfaf4485ddc2acd2096f933R185), it only changed casing since CS assumes no errors in the code (and Object is an error), but `use Riak\Object` is still there and it was broken before too.

Looks to have been fixed in https://github.com/doctrine/cache/commit/f9be2e59866e1c7794e8d5c27c57c96cf51365a4

**Comment by Ocramius** [comment]
Riak support dropped
