### ISSUE TITLE
[Question] Will this package implement PSR-16 interfaces?

### ISSUE THREAD

**Issue by mimmi20** [doctrine/cache#300]
Actually I use a wrapper to connect a library that I use (which requires a PSR-16 cache interface) and this library. I want to remove the dependency to this wrapper.

Is it possible to update the cache interface this library is using, or shall I write a cache driver?

**Comment by Ocramius** [comment]
See https://github.com/Roave/DoctrineSimpleCache

This package won't change API: existing wrappers already provide such commodity layer.
