### ISSUE TITLE
Doctrine\Common\Cache\FlushableCache::flushAll() async?

### ISSUE THREAD

**Issue by fridde** [doctrine/cache#301]
This is definitely not a bug, but *maybe* a missing part in the docblock-documentation.

I have just been putting in an hour trying to understand a weird behaviour. Consider this:

``` lang-php
$cache = new \Memcached();
$cache->addServer(...$args);  // $args are already defined elsewhere

$this->cache = new MemcachedCache();
$this->cache->setMemcached($cache);

// consider $recently_deployed to reflect that I recently updated my app in production
if($recently_deployed){   
    $this->cache->flushAll();
    echo "Cache should be empty now! . PHP_EOL");
}

echo ($this->cache->contains('settings') ? 'Settings still in cache' : 'Settings flushed from cache');
```

The output was not at all what I expected: 
    
    Cache should be empty now!
    Settings still in cache

I now understand that ```flushAll()``` seems to be an async function when using Memcached and I guess a new thread is started.

My question: Should the docblock in 

https://github.com/doctrine/cache/blob/bdf3e32d07a8978c713a726d9bc60b7fa6b4dbff/lib/Doctrine/Common/Cache/FlushableCache.php#L13

mention that you can't rely on the cache being flushed after the execution of the function (for certain implementations of FlushableCache) or is this common knowledge?

**Comment by greg0ire** [comment]
This sounds like a bug in memcached, maybe try to reproduce it without php (with a bash script?), and report it at https://github.com/memcached/memcached/issues

**Comment by fridde** [comment]
@greg0ire I thought about that, too, but I'm only encountering this behaviour in a hosted environment. 

My belief is that the latency on my localhost is too short for this effect to occur, i.e. the time for php to run ```$this->cache->flushAll()``` until ```$this->cache->contains('settings')``` is longer than the memcached demon needs to flush. On the production server the time relation is reversed.

**Comment by greg0ire** [comment]
Maybe you could try calling https://secure.php.net/manual/en/memcached.getresultcode.php between the 2 two calls, see if any unexpected result code is sent back

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
