### ISSUE TITLE
`add` method for MemcachedCache

### ISSUE THREAD

**Issue by ilyachase** [doctrine/cache#305]
**Description**
In Memcached there is add operation: https://www.php.net/manual/ru/memcached.add.php
And it's very useful since it's atomic and safe from race condition operations. It can be used as a locks mechanism, for example.
But we don't have this method in MemcachedCache for some reason. I understand that there is no such method in `\Doctrine\Common\Cache\Cache` interface but still since it's MemcachedCache why can't we add it here? And then if it's okay for some applications to rely on MemcachedCache class and not on Cache interface, add method will be available for them.

**Example**
```php
$m = new Memcached();
$m->addServer('localhost', 11211);

$cacheDriver = new \Doctrine\Common\Cache\MemcachedCache();
$cacheDriver->setMemcached($m);
$check = $cacheDriver->add('test', true, $expire);

if (!$check) {
  echo 'Item was already added!';
}
```

**Comment by Ocramius** [comment]
@ilyachase I'd rather say that if you rely on such specific `Memcached` mechanism, you should not rely on the `Doctrine\Common\Cache\Cache` itself directly, but rather on your `Memcached` instance.
