### ISSUE TITLE
PhpFileCache performance regression in 1.7.0

### ISSUE THREAD

**Issue by ramunasd** [doctrine/cache#309]
PhpFileCache is slower in versions >=1.7.0  in comparison with v1.6.2

This is either missing file warning supression or data serialization.

Tested under high load conditions.

**Comment by Ocramius** [comment]
Could you maybe design a performance test to verify this?

**Comment by ramunasd** [comment]
Sure @Ocramius , will do it with phpbench.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
