### ISSUE TITLE
In ApcuCache, apcu_fetch() emits E_NOTICE

### ISSUE THREAD

**Issue by Piskvor** [doctrine/cache#310]
If the APCu read fails, an E_NOTICE is emitted; most frameworks will handle errors by converting to \ErrorException. For a cache read fail, this is overly drastic (as it can be handled as a cache miss).

Therefore, I propose silencing the apcu_fetch() call.

**Comment by Piskvor** [comment]
Pull request: #311

**Comment by cybernet** [comment]
can it be closed ?

**Comment by greg0ire** [comment]
@cybernet why? The pull request is not merged…

**Comment by cybernet** [comment]
so, usually takes about a year to merge ?

**Comment by greg0ire** [comment]
I don't know how you can get that kind of statistics, tell me if you manage to do so.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
