### ISSUE TITLE
RedisCache delete is deprecated

### ISSUE THREAD

**Issue by flaushi** [doctrine/cache#313]
I am using v 1.8.0.
 I get the following notice:
```
php.INFO: Deprecated: Function Redis::delete() is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Function Redis::delete() is deprecated at /var/www/symfony/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:126)"} []
```
my ext-redis was installed via `pear install redis` and has version 5.0.2

**Comment by Ocramius** [comment]
@flaushi I think #312 may fix that issue for you.

@doctrine/doctrinecore  I think we should start splitting out the various adapters, locking them onto specific extension versions, and use @maglnet `/composer-require-checker` against our own libs :-\

**Comment by lcobucci** [comment]
https://github.com/doctrine/cache/releases/tag/v1.8.1 released to solve this.
