### ISSUE TITLE
DoctrineNamespaceCacheKey and some keys are unreachables

### ISSUE THREAD

**Issue by Antjac** [doctrine/cache#315]
Hi,

I've a key "DoctrineNamespaceCacheKey[namespace]" which contain an interator : "**i:3**"; by exemple. I don't know why and when it iterates.

But, in this case,  only the keys with namespace_[nameofmykey][**3**] are reachable
the same key but with another iterator (namespace_[nameofmykey][**2**]) is unreachable

Could you tell me why it iterates and how can I do to prevent it ?

Thx,

**Comment by Ocramius** [comment]
It is supposed to be an `integer`, not an iterator: https://3v4l.org/m8pG6

The rationale for this namespacing is to allow complete replacement of the cache, without having to delete pre-existing keys on eviction.

**Comment by Antjac** [comment]
I totally understand but in my case i would like to disable it (or to keep control)...
I use Redis cache each night to keep in cache the result of a long time query. And randomly (it seems to be), this integer change and the result of the night is unreachable...

How can i do ?

**Comment by Ocramius** [comment]
> And randomly (it seems to be), this integer change and the result of the night is unreachable...

This is because it was incremented due to a cache eviction.

https://github.com/doctrine/cache/blob/c29471b93a163e79674d1928ec996916f509178c/lib/Doctrine/Common/Cache/CacheProvider.php#L150-L165

**Comment by Antjac** [comment]
Thanks a lot
