### ISSUE TITLE
Cache is never cleared

### ISSUE THREAD

**Issue by Dadibom** [doctrine/cache#316]
There's a possibility that this affects _all_ caches (incl metadata) and not just query cache, but what i've looked at is the query cache specifically.

Clearing the query cache does not actually remove anything from the cache. instead, a new namespace is set. since there is no ttl on query cache by default (and i have not found any way to set one), these old entries will remain forever and eat up the cache space.

**Comment by Ocramius** [comment]
Closing as per @lcobucci's comment.
