### ISSUE TITLE
Support RedisCluster?

### ISSUE THREAD

**Issue by Webonaute** [doctrine/cache#333]
Is it possible to implement support for RedisCluster? It will be a great help for our infrastructure.

**Comment by alcaeus** [comment]
We are currently in the process of deprecating this cache library and are no longer working on adding new features. I would recommend switching to `symfony/cache`, which supports configuring clusters for their Redis adapter: https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

**Comment by Webonaute** [comment]
@alcaeus how do I use Redis adapter with Doctrine in a symfony app then?
I try to use SNC_REDIS bundle who support also RedisCluster and following configuration documentation and endup with same doctrine error Argument 1 passed to Doctrine\Common\Cache\RedisCache::setRedis() must be an instance of Redis, instance of RedisCluster given

**Comment by alcaeus** [comment]
Please look at https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle and check other Symfony documentation on how to configure caches. I suppose you're using DoctrineBundle, at which point you can use the `pool` cache setting for whatever cache you want to have in Redis ([see docs](https://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html#caching-drivers)). If you have any other questions, please feel free to drop us a line in the #doctrine channel in the Symfony-Devs slack, or open an issue at DoctrineBundle.
