### ISSUE TITLE
mkdir is affected by default `umask()` setting

### ISSUE THREAD

**Issue by psafarov** [doctrine/cache#345]
https://github.com/doctrine/cache/blob/5c5b0e27f6a8d2e03b1bdd061bd9056c4e9d1cf6/lib/Doctrine/Common/Cache/FileCache.php#L222
If you pass `0000` as umask parameter, the resulting directory will still have `0755` as `mkdir` call is affected by default php `umask()` setting which is `0002`.
```php
new Doctrine\Common\Cache\FileCache($path, $extension, 0000)
// Permissions expected: 0777, actual: 0755
```

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
