### ISSUE TITLE
Suggestion: Refactor code to replace the name "cache" as a directory name

### ISSUE THREAD

**Issue by humantex** [doctrine/cache#349]
I know this will sound like an outrageous suggestion on face value, but there's a valid reason.

Shared hosting providers offering automated backup solutions to end users are aggressively using exclude filters that are not modifiable by those users. If they gloabally, and recursively, set the name "cache" in the exclude list, any directory that matches is ignored from the backup. If a site needs restoration from any previous backups, the restored site will likely be inoperative.

Jetbackup on cPanel is set up this way, and I suspect that other offerings allow for the same global excludes to be set. If this is done in an arbitrary way to 'refine' backups to not include temporary files as a time/space saving strategy, it affects functionality when a library's naming conventions collide with the filter's intent. No attempt is made to determine what the actual directory or it's contents are, and if they are in fact unnecessary folders/files.

This is a scenario that I've had to deal with for the past week, where a site I tried to restore turned into a brick. The entire '/modules/cache' directory in the CMS was ignored and rendered the site useless when it's missing.

That issue is here as a reference: https://github.com/biskuitorg/biskuit/issues/73

I've also contacted Jetbackup, and have a ticket started with them to see if they can offer any assistance. I can update with any responses I get, if that might be helpful.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
