### ISSUE TITLE
Lazy Redis connection

### ISSUE THREAD

**Issue by BackEndTea** [doctrine/cache#365]
Currently we're using a custom redis adapter that only connects to redis once it actually needs to do something.

Would such an implementation be useful to have in this package? If so i'd be happy to provide a PR.

**Comment by stof** [comment]
Given that doctrine/cache is being sunset (see https://github.com/doctrine/cache/issues/354), I don't think this should be added in this package.

Note that symfony/cache already has such a feature to connect to Redis lazily.

**Comment by BackEndTea** [comment]
Ah, i wasn't aware of that. Thanks for the info!
