### ISSUE TITLE
The typehint for the CacheAdapter constructor is wrong

### ISSUE THREAD

**Issue by stof** [doctrine/cache#369]
The CacheAdapter (part of the PSR-6 compat layer) typehints its argument as `Cache`, while the implementation actually relies on `Cache&MultiGetCache&MultiDeleteCache&MultiPutCache&ClearableCache`. The constructor should check for that (and https://github.com/doctrine/persistence/pull/182 might need to update its checks, unless `CacheAdapter::wrap` becomes responsible for validating that type).

/cc @alcaeus

**Comment by stof** [comment]
Note that this is probably the reason why the symfony/cache adapter enforced using `CacheProvider` as the type, as this base class implements all these interfaces (and more)

**Comment by alcaeus** [comment]
Fixed in #370.
