### ISSUE TITLE
Is there a docs for v2?

### ISSUE THREAD

**Issue by simPod** [doctrine/cache#378]
Hi, I've checked https://www.doctrine-project.org/projects/doctrine-cache/en/2.0/index.html and there seems to be removed adapters listed so I'm thinking it's not updated yet, right?

**Comment by greg0ire** [comment]
Right 👍 Please send a PR :pray:

**Comment by alcaeus** [comment]
I forgot to remove obsolete documentation. I've fixed this in the PR above.
