### ISSUE TITLE
Crash in Doctrine/ORM/Tools/Setup/createCacheInstance() after composer update

### ISSUE THREAD

**Issue by rmunitz** [doctrine/cache#385]
After doing a composer update, my application is crashing in Doctrine/ORM/Tools/Setup/createCacheInstance().  The update installed doctrine/orm version 2.9.3.
I understand that this is due to the dropping of direct cache support in doctrine/cache 2.1, which has eliminated the ArrayCache class that the crashing code is attempting to auto-load, but failing to do.  The crash is occurring on a line that is attempting to check for the existence of that class, and would have thrown the following exception had it not crashed: 
"Setup tool cannot configure caches without doctrine/cache 1.11 or symfony/cache. Please add an explicit dependency to either library."
First I added and installed symfony/cache. It still crashed. Then I added an explicit dependency: "doctrine/cache": "^1.11". It installed 1.12 and everything started working again.
However, I'd prefer to make the necessary changes to my application so that I can use latest supported versions going forward rather than forcibly pin myself to an eventually unsupported version.  My question is how do I do that?  https://github.com/doctrine/cache/issues/354 instructs us as follows: "if your package uses any cache implementation, you should find a suitable alternative and replace usages."
In my case, however, it is not my application code that is referencing a cache implementation. My bootstrap code is simply calling a function that is part of doctrine/ORM out of the box: Setup::createAnnotationMetadataConfiguration() without specifying cache - i.e. use default behavior. It is the call chain that follows from there that is ultimately referencing the missing cache class in Setup/createCacheInstance(). That is not my code to modify.  
So my question is: what is the proper way to migrate my application's call to Setup::createAnnotationMetadataConfiguration() with doctrine/cache V2 installed so that it is either specifying a supported Cache object, or preferably so that the default behavior for this function when no Cache object is passed internally uses a default that no longer crashes or throws an exception. I can't find any documentation that addresses this.
Thank you!

**Comment by greg0ire** [comment]
Can you please produce [a stack trace](https://symfony.com/doc/current/contributing/code/stack_trace.html) for the crashes you mention? :pray:

**Comment by rmunitz** [comment]
Stack trace:
Call Stack
--

1 | 0.0086 | 410472 | {main}( ) | ...\index.php:0
2 | 0.0131 | 411224 | include_once( 'C:\wamp64\www\usbgf\src\usbgf_bootstrap.php' ) | ...\index.php:12
3 | 0.0157 | 434952 | Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration( ) | ...\usbgf_bootstrap.php:30
4 | 0.0157 | 434952 | Doctrine\ORM\Tools\Setup::createConfiguration( ) | ...\Setup.php:87
5 | 0.0157 | 434952 | Doctrine\ORM\Tools\Setup::createCacheConfiguration( ) | ...\Setup.php:139
6 | 0.0157 | 434952 | Doctrine\ORM\Tools\Setup::createCacheInstance( ) | ...\Setup.php:160
7 | 0.0157 | 434952 | class_exists ( ) | ...\Setup.php:183
8 | 0.0157 | 435016 | spl_autoload_call ( ) | ...\Setup.php:183
9 | 0.0158 | 435080 | usbgf_src_AutoLoad( ) | ...\Setup.php:183

The call in (2) to Setup::createAnnotationMetadataConfiguration() is below. Note that parameter 4 - the Cache - is not being passed and defaults to null.
$config = Setup::createAnnotationMetadataConfiguration($entitySourceDirs, $isDevMode, $PROXY_DIR);

In case it is of value, here is what I have installed that produced the above stack trace:
$ composer show |grep doctrine
doctrine/annotations                 1.13.1    Docblock Annotations Parser
doctrine/cache                       2.1.1     PHP Doctrine Cache library is a popular cache implementation that s...
doctrine/collections                 1.6.7     PHP Doctrine Collections library that adds additional functionality...
doctrine/common                      3.1.2     PHP Doctrine Common project is a library that provides additional f...
doctrine/dbal                        2.13.2    Powerful PHP database abstraction layer (DBAL) with many features f...
doctrine/deprecations                v0.5.3    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 l...
doctrine/event-manager               1.1.1     The Doctrine Event Manager is a simple PHP event system that was bu...
doctrine/inflector                   2.0.3     PHP Doctrine Inflector is a small library that can perform string m...
doctrine/instantiator                1.4.0     A small, lightweight utility to instantiate objects in PHP without ...
doctrine/lexer                       1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, Rec...
doctrine/orm                         2.9.3     Object-Relational-Mapper for PHP
doctrine/persistence                 2.2.1     The Doctrine Persistence project is a set of shared interfaces and ...

**Comment by dopeh** [comment]
I'm running into the same issues. It is clear that doctrine/orm v2.9.3 is not compatible with doctrine/cache v2.1 (as v2.9.3 has a [check](https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/Tools/Setup.php#L183) if `ArrayCache` exists, which has been removed from v2.1.1.), but the composer constraints in `doctrine/orm` don't prevent this upgrade.

The composer.json of `doctrine/orm` of 2.9.x allows doctrine/cache 2.1, which allows this upgrade from v1.X to v2 to happen (see https://github.com/doctrine/orm/blob/2.9.x/composer.json#L24).

It looks like it already has its own issue (https://github.com/doctrine/orm/issues/8809) and will need to be fixed in doctrine/orm.

**Comment by greg0ire** [comment]
Thanks for digging that up @dopeh !
