### ISSUE TITLE
Performance degradation due to subsequent commit of deferredItems in PSR6 CacheAdapter

### ISSUE THREAD

**Issue by holtkamp** [doctrine/cache#386]
It noticed a significant performance degradation when persistent caches were empty and generating around 250 Doctrine Proxies. 

For Entity Metadata I use a ChainCache with the following CacheProviders:

- ArrayCache, for "in request" storage
- ApcuCache, for "in between request" storage
- PDOMySQL, for persistent storage

When monitoring the MySQL database, I noticed that a big amount of INSERT queries were performed: around 68k.

![Screenshot 2021-07-16 at 16 35 07](https://user-images.githubusercontent.com/776405/125970509-7df0f38d-1d54-4f03-a605-a382ce6869a8.png)

I traced this back to the following behaviour:

- when fetching Entity Metadata, CacheAdapter::getItems() is invoked
- in CacheAdapter::getItems(), when ["deferredItems" are detected CacheAdapter::commit() is invoked](https://github.com/doctrine/cache/blob/ac77408b22cc6c4d0b4947d20a3889be3043566e/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L100-L102) to persist using doSaveMultiple()
- but because the CacheAdapter::deferredItems array is not cleared, it keeps on growing
- each time CacheAdapter::getItems() is invoked, a larger amount of deferredItems needs to be persisted

My question: is this expected behaviour? Should the stack of deferredItems not be emptied after successfully saving multiple items Something like:

```php
if($success){
    $this->deferredItems = [];
}
```

I now circumvented the described behaviour by keeping track what key was already saved to the persistent CacheProvider and prevent subsequent processing. Now the amount of queries is back to normal: around 1300. 

![Screenshot 2021-07-16 at 16 55 20](https://user-images.githubusercontent.com/776405/125970824-349d918e-681b-4d35-ab2c-a501e74076b2.png)

**Comment by stof** [comment]
this indeed looks like a bug introduced when copying the code of symfony/cache and inlining the code of the AbstractAdapter. The symfony/cache codebase resets the deferredItems in `commit`: https://github.com/symfony/cache/blob/81c7f2bbe0a9497c61c0530eab33e9d72d2b78f3/Adapter/AbstractAdapter.php#L151

/cc @alcaeus

**Comment by alcaeus** [comment]
@holtkamp thank you for that excellent analysis. I don't have time to work on it, so if anyone wants to take a shot at fixing this I'd really appreciate it.

**Comment by greg0ire** [comment]
I'm giving it a try.

**Comment by derrabus** [comment]
Please verify that #387 fixes the issue for you.

**Comment by holtkamp** [comment]
@greg0ire and @derrabus, yes, https://github.com/doctrine/cache/pull/387 fixes the issue. 

Thanks for the very response.

The only doubt I can think of: currently the `deferredItems` array is always cleared, regardless of the outcome of the actual operation by the CacheProvider. 

My initial thought would be to only clear the `deferredItems` when the involved CacheProvider successfully processed the items. 

But I suppose it will become too complex / is not the responsibility of this CacheAdapter to keep track of the outcome and only "clear" on successful operations... ?

**Comment by greg0ire** [comment]
@holtkamp this is indeed going to be complex, and would qualify as a new feature rather than a bug fix, so if it should be contributed, I think it should be contributed separately.

**Comment by greg0ire** [comment]
@holtkamp here is a good reason not to add complexity: https://github.com/doctrine/cache/pull/375#issuecomment-847839053

**Comment by holtkamp** [comment]
Thanks all for the swift response and clear communication!
