### ISSUE TITLE
Incorrect "mixed" type hint in TypedCacheItem

### ISSUE THREAD

**Issue by Sjord** [doctrine/cache#412]
[Here](https://github.com/doctrine/cache/blob/5d55089cbe7339f72405560a254153e21c24e9c5/lib/Doctrine/Common/Cache/Psr6/TypedCacheItem.php#L35):

    public function get(): mixed
    {
        return $this->value;
    }

This return type hint `mixed` isn't really a correct type hint. It resolves to Doctrine\Common\Cache\Psr6\mixed, which doesn't exist.

**Comment by stof** [comment]
Using `mixed` as return type is indeed wrong, as this native type requires PHP 8+ while this library supports 7.1+

**Comment by Sjord** [comment]
I wasn't aware that mixed became a valid type since PHP 8. The implicit fields in the constructor also seems to be specific to PHP 8:

```
    public function __construct(
        private string $key,
        private mixed $value,
        private bool $isHit,
    ) {
    }
```

**Comment by stof** [comment]
Actually, the code is not broken, because `TypedCacheItem` is used only on PHP 8: https://github.com/doctrine/cache/blob/5d55089cbe7339f72405560a254153e21c24e9c5/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L80-L92

**Comment by Sjord** [comment]
Interesting. Thanks.
